name: Deploy to Supabase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
    - uses: actions/checkout@v4

    - uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Deploy Functions
      run: supabase functions deploy --project-ref $PROJECT_ID
